- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Creates directory"
  file:
    path: "~/server"
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "artifact.tar.gz"
    dest: "~/server/artifact.tar.gz"

- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "~/server/artifact.tar.gz"
    dest: "~/server"

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/server
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready