- name: "Create backend directory"
  file:
    path: "~/backend"
    state: "directory"
    mode: 0755

- name: "Copy build folder"
  copy:
    src: "../../artifact.tar.gz"
    dest: "~/backend/artifact.tar.gz"

- name: "Extract build folder"
  unarchive:
    remote_src: yes
    src: "~/backend/artifact.tar.gz"
    dest: "~/backend"

- name: "Start server"
  shell:
    cmd: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start