---
- name: Ensure target directory exists
  file:
    path: /home/ubuntu/udapeople_app
    state: directory

- name: Copy backend package
  unarchive:
    src: /root/project/artifact-backend.tar.gz
    dest: /home/ubuntu/udapeople_app

- name: Build backend
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/udapeople_app
    npm i
    npm run build

- name: Stop and delete already running server
  ignore_errors: yes
  command: pm2 delete all

- name: Start server
  become: true
  environment:
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  shell: |
    cd /home/ubuntu/udapeople_app
    pm2 start npm -- run "start:dev"
  register: shell_output

- name: Print log of Start server shell command
  debug:
    var: shell_output.stdout_lines