- name: "Extract build folder"
  unarchive:
    remote_src: yes
    src: "artifact.tar.gz"
    dest: "~/"

- name: "Start server"
  shell:
    cmd: |
      npm install
      pm2 stop default
      pm2 start npm -- start