- name: "download node exporter."
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter-0.17.0.linux-amd64.tar.gz

- name: "unarchive node exporter."
  unarchive:
    remote_src: yes
    src: "/tmp/node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: "/tmp"

- name: "move node exporter to bin"
  become: true
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'
    
- name: "add node exporter config"
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes